# Generated by Django 4.2.30 on 2026-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="propertypost",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Owner's contact number", max_length=20, null=True
            ),
        ),
    ]
