# Generated by Django 4.2.30 on 2026-06-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_contact_phone_propertypost_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertypost",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
