# Generated by Django 4.2.30 on 2026-06-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertypost",
            name="sold_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propertypost",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
