# Generated by Django 4.2.30 on 2026-06-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
